<!doctype html>
<html lang='es'>
<head>
<title>SARA</title>
<meta charset='utf-8'>
<link rel='stylesheet' href='<?php echo base_url()?>css/bootstrap.min.css'>
<link rel="stylesheet" href="<?php echo base_url()?>css/jquery-ui.min.css">
<link rel="stylesheet" href="<?php echo base_url()?>css/sara.css">

<script src='<?php echo base_url()?>js/jquery.min.js'></script>
<script src='<?php echo base_url()?>js/bootstrap.min.js'></script>
<script src="<?php echo base_url()?>js/jquery-ui.min.js"></script>
<script src="<?php echo base_url()?>js/logeo.js"></script>

</head>
<body>	
	<div style="text-align:center;">
	<h3>INGRESAR</h3>
	<div id="mensaje" type='text'> </div>
	Usuario: &nbsp; &nbsp; &nbsp;<input type='text' id='usuario'><br>
	Contraseña: <input type='password' id='clave'><br>
	
	<button type="button" id="log_butt" style='width:70px; height:25px'>Ingresar</button>
</div>

</body>
</html>