ed: {0}
MSG_ConnectionLost=The connection to the MySQL Server was lost.  The connection may have timed out, the network connection may have been lost, or the server may have been shut down.
MSG_QueryReconnect=Do you want to try to reconnect to the server?
MSG_ServerNoLongerRunning=The MySQL Server appears to no longer be running.  It may have been stopped or the network connection may have been lost.  Please check the status of the MySQL server and restart if necessary.
MSG_ServerStillRunning=It appears the stop command did not succeed or has not completed, as the MySQL server still appears to be running.  The server may still be shutting down, or you may need to adjust your settings for the stop command, or you may need to stop the server manually.\n\nDo you want to keep waiting for the server to start or edit your settings for the stop command?
MSG_ConnectFailedAfterStart=Unable to connect to the MySQL server after starting it: {0}.
MSG_DatabaseCommandFailed=The database command {0} failed with the following exception: {1}
MSG_InvalidPortNumber=Invalid port number {0}.  Please edit the MySQL properties and change the port number.
MSG_UnknownHost=Unknown host {0}.  The network may be down or you may have set the host name to an invalid name.
MSG_StartingMySQL=Starting MySQL Server...
MSG_StoppingMySQL=Stopping MySQL Server...
MSG_ReconnectFailed=Unable to connect to the MySQL server:\n\n{0}.\n\nThe server may not be running or your MySQL connection properties may not be set correctly.  Do you want to edit your MySQL connection properties?
MSG_ServerDoesNotAppearToHaveStarted=Unable to connect to the MySQL server after startup: {0}.\n\nIt could still be starting up, or you may need to change your settings for the start command or your connection settings.\n\nDo you want to edit your MySQL properties or keep waiting for the server to start up?
MSG_UnableToReconnectServerNotRunning=Unable to connect to the MySQL server because it is does not appear to be running at the configured host ({0}) and port ({1}).  Please check that the server is running and that your configuration settings are correct.
MSG_ReconnectingToMySQL=Reconnecting to the MySQL server
MSG_WaitingForServerToStart=Waiting for MySQL Server to start
MSG_WaitingForServerToStop=Waiting for MySQL Server to stop
MSG_CantStartServerIsAlreadyRunning=Unable to start the MySQL server because it appears to be already running at host {0}, port {1}.  Please try connecting to the server. It is also possible another process is listening on that port.
MSG_CheckStart=The settings for starting MySQL have changed.  Do you want to start the server now?
MSG_UnableToStopServer=Encountered an error while trying to stop the MySQL server
MSG_UnableToStartServer=Encountered an error while trying to start the MySQL server
MSG_NoSampleWithoutInnoDB=The sample requires the InnoDB storage 